20.Б10-мм, Дегтярев Иван, homework 1 tasks 1-5
Degiv/spbu_2020_c_homeworks pull request #1
Opened 2020-09-22 20:49 UTC by Degiv

2020-09-22 22:46 UTC, khodand commented on homework_1/hw1.5/main.c
> +}
😳

2020-09-25 12:37 UTC, SpirinEgor requested changes
Решения хорошие, но пр оформлен был неверно (не добавил меня в reviewer), поэтому так поздно пришёл фидбек

2020-09-25 12:37 UTC, SpirinEgor commented on .github/workflows/build_with_lint.yml
> +name: Build_with_lint
Не надо трогать файлы, которые отвечают за CI и тому подобное. В пр должна быть информация только о текущей задаче.

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.1/main.c
> +            //cin >> numbers[i][j];
Ну это что-то не из мира C...
Так что странно даже видеть в комментариях подобное

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.1/main.c
> +    int** numbers = (int**)malloc(n * sizeof(int*));
Лучше использовать calloc, так как он ещё нулями проинициализирует.
А при таком создание как раз и не хватает инициализации

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.2/main.c
> +}
Эти функции вполне можно вынести в библиотеку. swap в numericOperations, а reverse в arrayOperations

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.3/main.c
> +    inputString(s1, m);
Кажется, что использовать scanf для чтения всей строки или даже fgets куда удобнее (в 2 раза меньше кода и не надо дополнительно длину строки спрашивать).
Для получения длины строки можно использовать strlen

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.5/main.c
> +}
Опять же, swap уже был реализован в другой задаче. Если его вынести в библиотеку, то не надо будет копировать его везде

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.5/main.c
> +void buildHeap(int* numbers, int n)
Хорошее решение!
Я бы опять же предложил перенести кучу в либу, куда-нибудь в heap.h/heap.c
Не уверен, но в следующих домашних работах может понадобится это всё

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.5/main.c
> +int findSeveralMax(int* numbers, int n, bool* isFound)
(эту функцию никуда переносить не надо, она относится именно к этой задаче)

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.5/main.c
> +    int severalMax = findSeveralMax(numbers, n, &isFound);
Обычно делают наоборот: передают адрес, куда положить ответ, а возвращают bool

2020-09-25 12:37 UTC, SpirinEgor commented on homework_1/hw1.5/main.c
> +    int severalMax = findSeveralMax(numbers, n, &isFound);
Тогда можно более аккуратно писать
```
if (findSeveralMax(...)) {
    ...
}
```

2020-09-25 12:54 UTC, Degiv commented on homework_1/hw1.1/main.c
> +            //cin >> numbers[i][j];
> Ну это что-то не из мира C...
> Так что странно даже видеть в комментариях подобное

Сначала отправил решения на плюсах по ошибке, потом переделывал

2020-09-29 07:46 UTC, SpirinEgor approved these changes

2020-09-29 07:46 UTC, SpirinEgor commented on library/commonUtils/arrayOperations.h
> +#pragma once
Вместо pragma лучше использовать ifndef/endif

2020-09-29 07:46 UTC, SpirinEgor commented on library/commonUtils/heap.h
> +#pragma once
опять же, надо дефайны использовать

2020-09-29 07:46 UTC, SpirinEgor commented on homework_1/hw1.1/main.c
> +    printf("%d", numbers[firstIndex][firstIndex]);
Тут пробела не хватает, первые 2 числа склеиваются

2020-09-29 07:48 UTC, SpirinEgor requested changes

2020-09-29 07:48 UTC, SpirinEgor commented on homework_1/hw1.1/main.c
> +    printf("%d", numbers[firstIndex][firstIndex]);
Случайно approve поставил, тут всё равно надо поправить. И pragma тоже

2020-09-29 07:49 UTC, SpirinEgor commented
А ещё надо конфликты разрешить

2020-09-30 19:04 UTC, SpirinEgor approved these changes

2020-09-30 19:09 UTC, merged