20.Б10-мм, Дегтярев Иван, task4.1
Degiv/spbu_2020_c_homeworks pull request #10
Opened 2020-10-11 00:26 UTC by Degiv

2020-10-14 12:47 UTC, SpirinEgor commented
Не прошла проверка стайлгайда

2020-10-14 16:22 UTC, Degiv commented
@SpirinEgor поправил

2020-10-17 17:46 UTC, SpirinEgor requested changes

2020-10-17 17:46 UTC, SpirinEgor commented on library/commonUtils/stack.c
> +StackElement* createStackElement(double value)
Ты хоть запускал?) Оно же не работает, падает моментально из-за этой функции

2020-10-18 11:04 UTC, Degiv commented on library/commonUtils/stack.c
> +StackElement* createStackElement(double value)
Запускал, у меня почему то работает такое, уже второй раз не замечаю подобную ошибку из-за этого

2020-10-21 13:54 UTC, SpirinEgor requested changes

2020-10-21 13:54 UTC, SpirinEgor commented on library/commonUtils/arrayOperations.c
> +            realloc(string, newSize * (sizeof(char)));
А сохранить указатель на новый массив?
valgrind сразу ругается, достаточно было с ним проверить

2020-10-23 14:13 UTC, SpirinEgor approved these changes

2020-10-23 14:14 UTC, merged