20.Б10-мм, Дегтярев Иван, task 5.1
Degiv/spbu_2020_c_homeworks pull request #18
Opened 2020-10-25 23:45 UTC by Degiv

2020-10-25 23:51 UTC, Degiv commented
Я правильно понимаю, что чтобы переиспользовать потом в авл структуры, придется их тела в хедер перенести?

2020-10-26 10:40 UTC, SokolovYaroslav commented
> Я правильно понимаю, что чтобы переиспользовать потом в авл структуры, придется их тела в хедер перенести?

Постараюсь сегодня вечером ответить на этот вопрос.

2020-10-27 08:26 UTC, SokolovYaroslav commented
Да, сорри что не вчера вечером :)
Нет, так делать точно не нужно.

В целом можно это всё сделать в рамках одной пары хэдера и сишника. Мол пусть там будет и такое дерево и другое.

А если делать в разных, то тогда придётся писать интерфейсы для изменения структур. Но надо их как-то по-особому называть наверное, потому что дёргание таких интерфейсов может всё сломать.

2020-10-27 11:45 UTC, Degiv commented
Пока что не стоит проверять, я для вопроса реквест сделал

2020-10-27 14:13 UTC, SokolovYaroslav commented
Ок, тегай как можно будет

2020-11-07 22:24 UTC, Degiv commented
@SokolovYaroslav готово к проверке

2020-11-20 11:51 UTC, SokolovYaroslav requested changes

2020-11-20 11:51 UTC, SokolovYaroslav commented on homework_5/hw5.1/main.c
> +}
Не очень похоже на интерактивщину

2020-11-20 11:51 UTC, SokolovYaroslav commented on library/commonUtils/BST.c
> +    node->counter = 1;
Что за каунтер и зачем он нужен?
По опыту проверки могу сказать, что он лишний :)

2020-11-20 11:51 UTC, SokolovYaroslav commented on library/commonUtils/BST.h
> +typedef struct BinarySearchTreeNode BinarySearchTreeNode;
Нода лишняя в интерфейсе. Юзеру о ней знать совершенно незачем: он чиселки вставляет в дерево, а не ноды

2020-11-26 17:02 UTC, SokolovYaroslav commented
Так, ну окей. Видимо надо так выставлять баллы за то, что есть
Ты заслал до софта, так что половить не будем

- Интерактивного формата нет -- -20%
- Нода в интерфейсе -- -10%
- Какой-то каунтер, без которого можно было обойтись -- -20%
- Из-за отсутствия интерактивного ввода сложно искать баги, поэтому представим, что они есть -- -10%

Получается 2 * 0.4 = 0.8

2020-11-26 17:02 UTC, closed without merging