20.Б10-мм, Дегтярев Иван, task2.1
Degiv/spbu_2020_c_homeworks pull request #2
Opened 2020-09-27 09:50 UTC by Degiv

2020-09-28 09:18 UTC, nbirillo requested changes

2020-09-28 09:18 UTC, nbirillo commented on homework_2/hw2.1/main.c
> +#include <malloc.h>
![image](https://user-images.githubusercontent.com/8993915/94413664-0e2be280-0184-11eb-835e-59ab6aab2aa7.png)
У меня это работать не будет :) Используй заголовочные файлы, которые работают на всех системах (такие есть и там определены `calloc` и `free`, которые ты используешь)

2020-09-28 09:18 UTC, nbirillo commented on homework_2/hw2.1/main.c
> +    free(parts);
У тебя `main` возвращает `int`, а ты ничего не возвращаешь)

2020-09-28 09:18 UTC, nbirillo commented on homework_2/hw2.1/main.c
> +    int* parts = (int*)calloc(n + 1, sizeof(int));
Лучше использовать `memset`, чтобы заполнить массив дефолтным значением после выделения памяти. Неинициализированная память - это плохо

2020-09-28 12:31 UTC, Degiv commented on homework_2/hw2.1/main.c
> +    int* parts = (int*)calloc(n + 1, sizeof(int));
Но ведь calloc() инициализирует память нулями, разве нет?

2020-09-28 17:29 UTC, nbirillo reviewed
Поправь тогда с memset и можно будет зачесть

2020-09-28 17:29 UTC, nbirillo commented on homework_2/hw2.1/main.c
> +    int* parts = (int*)calloc(n + 1, sizeof(int));
Действительно, сори) Тогда можешь убрать memset, хорошо, что заметил

2020-09-29 09:25 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-29 09:25 UTC, merged