20.Б10-мм, Дегтярев Иван, task2.2
Degiv/spbu_2020_c_homeworks pull request #3
Opened 2020-09-27 10:57 UTC by Degiv

2020-09-28 09:29 UTC, nbirillo requested changes

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    const int n = 4;
Давай это значение будет вводиться с клавиатуры пользователем с ограничением. Нижнюю границу выбери сам (например, 4 можно оставить), а верхняя - по количеству возможных уникальный цифр.

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    int secretNum[n];
Нужно инициализировать массив + он будет динамический, так как `n` будет вводиться пользователем. Не забудь только про освобождение памяти

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    int playerNum[n];
Массив надо инициализировать

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +        getPlayerNum(playerNum, n);
Здесь вероятно добавится проверка, что число в нужном диапазоне (см комментарии выше)

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    bool usedNumerals[numOfNumerals];
Массив нужно инициализировать и не церез цикл. Используй `memset`

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    tmp = getchar();
Можно считать сразу число и записать его в массив

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    }
Используй `memset` вместо цикла

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    }
Используй `memset` вместо цикла

2020-09-28 09:29 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +        }
Максимальная сумма быков и коров должна быть равна длине последовательности, то есть в данном случае 4, а у тебя 5:
![image](https://user-images.githubusercontent.com/8993915/94415428-2e5ca100-0186-11eb-8a99-10da44bc97b8.png)

2020-09-29 15:31 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    }
тут же не получится через memset

2020-09-29 20:08 UTC, nbirillo requested changes
Небольшие исправления остались

2020-09-29 20:08 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Ну memset обычно используется в связке с динамической памятью. Сейчас у тебя переменная все еще не инициализируется при создании сразу. Если у тебя остается не динамический массив, то используй `bool usedNumerals[numOfNumerals] = { false };` вот такое например, должно работать. Я предполагала, что если ты будешь использовать memset, тогда в этой строчке будет выделение памяти

2020-09-29 20:08 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +        areChecked[secretNum[i]] = true;
Сори, да. Тут я не заметила, тут все ок)

2020-09-29 20:08 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +int main()
У тебя тут Valgrind варнинги кидает:
![image](https://user-images.githubusercontent.com/8993915/94610135-7c69c580-02a8-11eb-85cc-f0ca5afd2b11.png)

2020-09-29 22:44 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Не компилится так. А чем плох мемсет не на динамическом?
> bool usedNumerals[numOfNumerals] = { false };`

2020-09-29 23:05 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Компилится, если константу задать не через const int а через #define, не знаю, стоит так сделать? С memset вроде и так все работает, просто чуть медленнее, как я понял

> bool usedNumerals[numOfNumerals] = { false };

2020-09-29 23:21 UTC, Degiv commented on homework_2/hw2.2/main.c
> +int main()
К сожалению у меня windows и не могу проверить, надеюсь, что исправил

2020-09-30 07:58 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +int main()
А ты правда знаешь аналоги Valgrind для Windows, да?

2020-09-30 07:58 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Оно скомпилится, если ты напишешь `const int numOfNumerals = 10;`. У тебя ошибка, если ты не поставишь `const`. Это связано с тем, что тогда переменная может меняться и непонятно как выделять память. Но если ты указал, что она не меняется (то есть `const`), то все будет нормально

2020-09-30 08:00 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +int main()
Не исправил

2020-09-30 08:46 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
У меня же и так const int было, даже в это выделенном куске кода видно

2020-09-30 08:53 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
![image](https://user-images.githubusercontent.com/32798005/94664397-7fe66680-0313-11eb-862e-6b670321d8dc.png)

2020-09-30 09:05 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Я думаю это связано с тем, что const int при инициализации может присваивать значение, которое до этого изменялось, например вот так
`const int numOfNumerals1 = n;`
Поэтому массив считается variable-sized

2020-09-30 09:56 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Все еще интересует, какой у тебя компилятор) Самой стало интересно почему так, у меня таких проблем не было никогда
![image](https://user-images.githubusercontent.com/8993915/94671154-2afb1e00-031c-11eb-91d6-fa9c7d86e2b1.png)

2020-09-30 10:21 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
x86_64-8.1.0-release-posix-seh-rt_v6-rev0\mingw64

2020-09-30 10:43 UTC, Degiv commented on homework_2/hw2.2/main.c
> +int main()
Я понял в чем ошибка, но у меня теперь вопрос, можно ли считать, что пользователь вводит правильный размер числа, или выделять память с запасом

2020-09-30 10:51 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
поставил gcc 10.2.0 для windows, все такая же ошибка, может быть на винде так не работает вообще. Как мне сделать тогда? Может через дефайны, или динамическую память выделять?

2020-09-30 10:53 UTC, Degiv commented on homework_2/hw2.2/main.c
> +int main()
Можно конечно сделать так, что я у себя через дефайны буду запускать, а на проверку отправлять с const int, но не знаю насколько это хорошая идея

2020-09-30 10:59 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Можно конечно сделать так, что я у себя через дефайны буду запускать, а на проверку отправлять с const int, но не знаю насколько это хорошая идея

2020-09-30 11:01 UTC, Degiv commented on homework_2/hw2.2/main.c
> +int main()
@nbirillo готово к проверке

2020-09-30 11:06 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
А теперь еще и checker такое не принимает )

2020-09-30 11:08 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Я тогда верну #define

2020-09-30 13:26 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    memset(usedNumerals, false, numOfNumerals * sizeof(bool));
Возможно и правда в компиляторе дело, я никогда не писала на си под виндой и честно говоря, не знаю в чем там дело) это надо гуглить и разбираться. Тогда можешь оставить с #define пока что

2020-09-30 13:27 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +int main()
В этих задачах пока что можно считать, что правильный

2020-09-30 13:35 UTC, nbirillo requested changes

2020-09-30 13:35 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +        printf("Enter a number :\n");
![image](https://user-images.githubusercontent.com/8993915/94691885-8d631700-033a-11eb-8c64-8f160e4badd5.png)
Добавь проверку, что пользователь вводит число нормального размера (если что на скрине там вывод загаданного числа мой, у тебя оно не выводится, все ок)

2020-09-30 13:35 UTC, nbirillo commented on homework_2/hw2.2/main.c
> +    char number[numOfNumerals + 1];
ну у тебя опять нет инициализации :)

2020-09-30 14:09 UTC, Degiv commented on homework_2/hw2.2/main.c
> +    char number[numOfNumerals + 1];
я почему-то всегда считал, что такие массивы сами инициализируются нулями

2020-09-30 16:10 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-30 16:10 UTC, merged