20.Б10-мм, Дегтярев Иван, task2.4
Degiv/spbu_2020_c_homeworks pull request #4
Opened 2020-09-27 11:48 UTC by Degiv

2020-09-28 09:36 UTC, nbirillo requested changes
Почини утечки памяти

2020-09-28 09:36 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +#include "malloc.h"
Та же проблема, как и в предыдущей задаче - у меня с ним не запустится

2020-09-28 09:36 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +    }
Может лучше считать число и разбить его на массив?

2020-09-28 09:36 UTC, nbirillo commented on library/commonUtils/mysorts.c
> +            ++j;
Добавь скобки {}

2020-09-28 09:36 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +int main()
Не работает, если есть нули
![image](https://user-images.githubusercontent.com/8993915/94416186-349f4d00-0187-11eb-8f5e-e23b68055d77.png)

2020-09-28 15:10 UTC, Degiv commented on library/commonUtils/mysorts.c
> +            ++j;
а если for() в одну строчку, тоже добавлять скобки, или только для while()?

2020-09-28 15:51 UTC, Degiv commented on library/commonUtils/mysorts.c
> +            ++j;
И такой же вопрос про if()

2020-09-28 17:30 UTC, nbirillo commented on library/commonUtils/mysorts.c
> +            ++j;
Если там действительно что-то короткое без дополнительной вложенности, можно не добавлять. Но так как тут for, в который вложен while без скобок сложно читать

2020-09-28 17:30 UTC, nbirillo commented on library/commonUtils/mysorts.c
> +            ++j;
Это просто улучшает читабельность кода и ничего больше)

2020-09-28 17:34 UTC, nbirillo requested changes

2020-09-28 17:34 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +void showNumerals(int* numerals, int n)
Но теперь у тебя совсем неверно....
![image](https://user-images.githubusercontent.com/8993915/94466236-c9c33580-01c9-11eb-83c5-6d6a71e1412b.png)
В данном случае предполагается, что получится 4005

2020-09-28 17:34 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +int main()
Все еще не починил утечки

2020-09-29 09:31 UTC, nbirillo requested changes

2020-09-29 09:31 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +int main()
Предполагается, что такеи значения тоже будут работать
![image](https://user-images.githubusercontent.com/8993915/94540626-56640700-024f-11eb-8290-6e7651e4599b.png)

2020-09-29 09:31 UTC, nbirillo commented on homework_2/hw2.4/main.c
> +    }
Немного костыльно выглядит. Почему не поменять первый ненулевой с первым нулевым и потом просто спокойно себе выводить все значения?

2020-09-29 09:31 UTC, nbirillo commented on library/commonUtils/mysorts.c
> +void countingSort(int* numbers, int n, int first, int last)
Вообще на самом деле это прекрасно, что ты сделал свою сортировку, но есть и стандартные, которые работают скорее всего получше :) Но это так, мысли вслух

2020-09-29 09:57 UTC, Degiv commented on library/commonUtils/mysorts.c
> +void countingSort(int* numbers, int n, int first, int last)
Я думал, предполагается, что мы должны реализовывать все сами

2020-09-29 10:02 UTC, nbirillo commented on library/commonUtils/mysorts.c
> +void countingSort(int* numbers, int n, int first, int last)
Здесь можешь оставить сортировку уже эту, но вообще, насколько я знаю, вам можно тут использовать встроенную сортировку

2020-09-30 08:03 UTC, nbirillo requested changes
![image](https://user-images.githubusercontent.com/8993915/94659165-8ae9c880-030c-11eb-8184-66c0a3a41f1f.png)
Все остальное ок

2020-09-30 17:07 UTC, nbirillo approved these changes
Зачтено!

2020-09-30 17:07 UTC, merged