20.Б10-мм, Дегтярев Иван, task3.1
Degiv/spbu_2020_c_homeworks pull request #7
Opened 2020-09-27 18:59 UTC by Degiv

2020-10-09 20:25 UTC, SokolovYaroslav requested changes
Чет мне кажется, что либо Касаций списал у тебя, либо вы делали эту домашку вдвоем. Обе ситуации -- это плохо.

Сейчас это прям явно видно. Если в будущем будут хотя бы подозрения, то я поставлю 0 обоим.

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* newListElement = calloc(1, sizeof(ListElement));
Почему не `malloc`?

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +int size(List* list);
Обычно название функции -- это глагол

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#endif //SPBU_2020_C_LIST_H
Файлы без пустой строки в конце -- зло

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > size(list)) {
Отрицательная позиция -- ок?

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        value->prev = NULL;
Там ведь уже Нуллы, зачем снова это писать?

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        ++list->size;
Брр. Как-то нечитаемо. Будто `list` инкрементируем.

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +            list->tail = value->next;
Зачем эта строчка?

Бтв, у тебя кто-то списывал чтоль? Списывать нехорошо.

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +bool insert(ListElement* value, int position, List* list)
`value` -- очень неинтутивное название для элемента списка. так ведь называется его содержимое, судя по описанию структуры.

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > size(list)) {
В остальных функциях тоже нужна такая проверка.

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    while (iterator != 0 && iterator != value) {
Это такая проверка на `NULL`?

2020-10-09 20:25 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        ListElement* tmp = head(list);
`tmp` -- плохое имя. Можно придуматьч то-то лучше. Например, `to_delete`

2020-10-09 22:57 UTC, Degiv commented on library/commonUtils/list.c
> +            list->tail = value->next;
Репозитории открытые, я не знаю, может и списывал кто-то

2020-10-09 23:50 UTC, Degiv commented on library/commonUtils/list.c
> +        value->prev = NULL;
Я посчитал, что это не гарантируется, ну ок

2020-10-10 09:41 UTC, SokolovYaroslav requested changes
По поводу того, что нуллы не гарантируются -- но ведь в `createListElement` указатели инициализируются нуллами, так что если через него создавать, то гарантируется.

2020-10-10 09:41 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position < 0 || position >= getSize(list))
Один и тот же иф в разных местах выглядит по-разному. Можно было бы вообще вынести это условие в отдельную функцию и бед не знать.

2020-10-10 09:41 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +int locate(ListElement* newElement, List* list);
Это не совпадает с тем, что написано в .c

2020-10-10 10:51 UTC, Degiv commented on library/commonUtils/list.c
> +    if (position < 0 || position >= getSize(list))
Он немного разный, тут второе неравенство не строгое, а там строгое

2020-10-11 09:34 UTC, SokolovYaroslav requested changes

2020-10-11 09:34 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position >= getSize(list) || position < 0) {
А тут видимо забыл

2020-10-11 10:20 UTC, Degiv commented on library/commonUtils/list.c
> +    if (position >= getSize(list) || position < 0) {
@SokolovYaroslav добавил

2020-10-11 10:34 UTC, SokolovYaroslav approved these changes

2020-10-11 10:51 UTC, merged