20.Б10-мм, Дегтярев Иван, task3.2
Degiv/spbu_2020_c_homeworks pull request #8
Opened 2020-09-27 21:04 UTC by Degiv

2020-10-09 20:52 UTC, SokolovYaroslav requested changes
В задании написано, что нужно переиспользовать лист из прошлого задания.
А еще на тесте n=5 m=3 у меня упало.

2020-10-09 23:19 UTC, Degiv commented
@SokolovYaroslav я же переиспользую, циклический лист использует оттуда функции и структуры. А насчет теста, странно, я постараюсь понять почему, но вот у меня все работает
![image](https://user-images.githubusercontent.com/32798005/95638868-e3545f00-0a9e-11eb-81be-8ef7d038bf97.png)

2020-10-10 09:45 UTC, SokolovYaroslav commented
По поводу переиспользования согласен, да. Чет я не вчитался после того, как тест повалился.

Тест кстати до сих пор валится. Его надо энивей починить, но мб это будет полегче после ревью, так что давай я его сейчас сделаю

2020-10-10 09:47 UTC, SokolovYaroslav requested changes

2020-10-10 09:47 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.h
> +#endif //SPBU_2020_C_CYCLICLIST_H
Снова файл без пустой строки

2020-10-10 09:47 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +}
То есть `void` возвращаем?

2020-10-10 09:47 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +}
Мб в этом причина падения, хз

2020-10-10 11:08 UTC, Degiv commented on library/commonUtils/cyclicList.c
> +}
Не знаю почему это вообще работало

2020-10-11 09:55 UTC, SokolovYaroslav requested changes
Исправить неудобные интерфейсы и гуд

Сразу наверное могу сказать, что у меня есть подозрение, что не нужен никакой `currentIndex`

2020-10-11 09:55 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Уххх, как неудобно!

2020-10-11 09:55 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Ну то есть для этой конкретной задачи сгодиться, да. НО! Раз уж мы пишем библиотеку, а не модуль, то давайте хотя бы чуть чуть подумаем об удобстве интерфейсов.

Мне кажется, что пользователю библиотеки было бы удобно самому сделать какие угодно арифметические операции с индексами. Без нашей помощи.
От нас потребуется только правильно это интерпретировать. То есть предлагаю, чтобы `insertCyclic` принимал любой целый индекс и брал его по модулю, чтобы понять, какой именно индекс имел ввиду пользователь.

Ну то есть если у меня есть цикличный список длины 5, а я хочу вставить на -3 позицию, то это означает, что надо вставлять на вторую.

2020-10-11 09:55 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +bool deleteCurrent(CyclicList* cyclicList)
И тут давай сделаем человеческое удаление по индексу

2020-10-11 10:04 UTC, Degiv commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Я просто не очень понимал вообще суть циклического листа, если так. Получается пользователь и по модулю мог бы сам брать, и зачем тогда это все вообще

2020-10-11 10:06 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Ну...
Мог :)
Вроде никто не заставлял делать либу отдельную для циклического листа

2020-10-11 10:09 UTC, Degiv commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Поэтому я воспринял эту структуру как рулетку, которую можно крутить на сколько хочешь, и работать только с полученным элементом

2020-10-11 10:11 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Ладно, давай я узнаю, засчитывать ли какой-то очень странный велосипед

2020-10-11 10:12 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Ну на самом деле переиспользовал ты норм -- уже хорошо

2020-10-11 10:23 UTC, Degiv commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Тогда жду, что решите

2020-10-11 10:26 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Я узнал
Можешь не переделывать.

2020-10-11 10:27 UTC, SokolovYaroslav approved these changes

2020-10-11 10:36 UTC, Degiv commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Мержить самому можно?

2020-10-11 10:41 UTC, SokolovYaroslav commented on library/commonUtils/cyclicList.c
> +void increaseCurrentIndex(int increment, CyclicList* cyclicList)
Не

2020-10-11 10:52 UTC, merged